-- AlterTable
ALTER TABLE "Item" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Machine" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "MachineLocation" ALTER COLUMN "updatedAt" SET DEFAULT CURRENT_TIMESTAMP;
